---
# This role installs minisign from sources
- name: Check if minisign is installed
  ansible.builtin.command: "minisign -v"
  register: minisign_present
  ignore_errors: true
  changed_when: false

- name: Get minisign installed version
  ansible.builtin.shell: >
    set -o pipefail &&
    minisign -v | awk '{print $2}'
  args:
    executable: /bin/bash
  when: minisign_present is not failed
  changed_when: false
  register: minisign_current_version

- name: Install minisign
  import_tasks: install.yml
  when: minisign_present is failed or (minisign_current_version.stdout != minisign_version)
...