---
# This role installs minisign from sources
- name: Check if minisign is installed
  command: "minisign -v"
  register: minisign_present
  ignore_errors: True

- name: Get minisign installed version
  shell: >
    minisign -v | awk '{print $2}'
  when: minisign_present is not failed
  register: minisign_current_version

- name: Install minisign
  import_tasks: install.yml
  when: minisign_present is failed or (minisign_current_version.stdout != minisign_version)
...