---
# This role installs minisign from sources
- name: Check if minisign is installed
  ansible.builtin.stat:
    path: "{{ minisign_path }}"
  register: minisign_present

- name: Get minisign installed version
  ansible.builtin.shell: >
    set -o pipefail &&
    {{ minisign_path }} -v | awk '{print $2}'
  args:
    executable: /bin/bash
  when: minisign_present.stat.exists
  changed_when: false
  register: minisign_current_version

- name: Install minisign
  ansible.builtin.import_tasks: install.yml
  when: not minisign_present.stat.exists or (minisign_current_version.stdout != minisign_version)
...
